field_group.field_group_formatter_plugin.background_image:
  type: field_group.field_group_formatter_plugin.base
  label: 'Mapping for the background image formatter settings'
  mapping:
    image:
      type: string
      label: 'Image field to be used.'
    image_style:
      type: string
      label: 'Image style to be used.'
    hide_if_missing:
      type: boolean
      label: 'Whether to hide the field group when the image is missing.'
